version: '2'
services:
  test-ubuntu:
    container_name: alpine
    image: alpine
    restart: on-failure
    command: ["sleep","infinity"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
  zookeeper:
    image: quay.io/debezium/zookeeper:2.1
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:2.1
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  connect:
    image: debezium/connect-jdbc:2.1
    build:
      context: debezium-jdbc
      args:
        DEBEZIUM_VERSION: 2.1
    ports:
     - 8083:8083
    links:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    extra_hosts:
      - "host.docker.internal:host-gateway"
