# reference: https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/deployment/overview/
# reference: https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/deployment/resource-providers/standalone/docker/#session-mode-1

# docker-compose up -d

# Session Mode: one JobManager instance manages multiple jobs sharing the same cluster of TaskManagers
version: "2.2"
services:
  jobmanager:
    image: flink:1.16.0-java11
    ports:
      - "8081:8081"   # dashboard: "localhost:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: flink:1.16.0-java11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2